server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect   # gợi ý: MySQL8Dialect đã deprecated

  data:
    redis:
      host: localhost
      port: 6379
      client-type: jedis       # >>> THÊM DÒNG NÀY <<<
      timeout: 5s              # (tuỳ chọn)

  cache:
    type: redis

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
