spring:
  config:
    activate:
      on-profile: mongodb

  data:
    mongodb:
      host: localhost
      port: 27017
      database: identity_service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

server:
  port: 8080
  servlet:
    context-path: /identity
